### ISSUE TITLE
Strange size for some dependecies

### ISSUE THREAD

**Issue by phil-r** [siddharthkp/cost-of-modules#16]
After running `cost-of-modules` on one of the projects, the largest dependency turned out to be `babel-preset-es2015` with the size of `320.52M` :
![image](https://cloud.githubusercontent.com/assets/577316/19851251/3e0b69d6-9f5d-11e6-8a78-dc2817b82308.png)
Although after running `cost-of-modules` on the clean repo with only `babel-preset-es2015` dependency the size was mere `14.55M` :
![image](https://cloud.githubusercontent.com/assets/577316/19851290/735a773a-9f5d-11e6-848d-5305265c72c5.png)

I guess something is wrong with the way size is calculated.

**Comment by siddharthkp** [comment]
Interesting. I look at the modules already installed in `node_modules` instead of doing a clean install.
This is for faster results, but it might have some weird results.

Notice that the number of children itself changed, can you give me a way to reproduce this? What were the other dependencies in the first screenshot?

**Comment by siddharthkp** [comment]
@phil-r Closing this, hit me up with some of this information when you can 😄

**Comment by phil-r** [comment]
@siddharthkp I've tested it recently - it's not the case anymore. Thanks!
