### ISSUE TITLE
Current project status

### ISSUE THREAD

**Issue by DanielRuf** [siddharthkp/cost-of-modules#58]
Hi, what is the current status of this project? Is it still maintained?

**Comment by fmagaldea** [comment]
I think you are wrong, first because language/dev criteria evolves + with quality/security tools your components is out of date because of security breach warnings, so I guess that the few projects - like mine - still using will soon just stop to.

But I understand it's hard to maintain something for years.

**Comment by siddharthkp** [comment]
> few projects like mine - still using will soon just stop to.

If you find it valuable and have some spare time, you might be able to patch it up over a couple of days

if not, I totally understand, I'm not using this tool anymore and would be happy to pass it on to someone else who does

**Comment by DanielRuf** [comment]
> if not, I totally understand, I'm not using this tool anymore and would be happy to pass it on to someone else who does

At least we would have to migrate to cli-table3 (https://github.com/siddharthkp/cost-of-modules/blob/master/package.json#L34), fix the failing build, move it to some org, invite contributors and a few more maintainers, ...

I could help with these things.

**Comment by siddharthkp** [comment]
> I could help with these things
That would be great, thanks!
